name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build macOS binary
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=${{ matrix.goarch }} go build -o dist/bravefm-darwin-${{ matrix.goarch }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/bravefm-darwin-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
